version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: dockerdemo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - singtel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dockerdemo"]
      interval: 30s
      timeout: 10s
      retries: 3

  ms2-service:
    build:
      context: ./MS2
      dockerfile: Dockerfile
    container_name: ms2-container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - singtel-network

  ms1-service:
    build:
      context: ./MS1
      dockerfile: Dockerfile
    container_name: ms1-container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - ms2-service
    networks:
      - singtel-network

volumes:
  postgres_data:

networks:
  singtel-network:
    driver: bridge